services:
  sandbox:
    container_name: sandbox
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - "./src:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.sandbox.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.sandbox.entrypoints=websecure"
      - "traefik.http.routers.sandbox.tls.certresolver=myresolver"
    networks:
      web:
      mariadb:
networks:
  web:
    name: web
    external: true
  mariadb:
    name: mariadb
    external: true
