name: Deploy on push
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: "jlb.ninja"
        username: "jdlxt"
        key: "${{ secrets.DEPLOY_KEY }}"
        script: |
          set -e
          cd ~/stack
          # check if repository exists
          if [ ! -d "dc_sandbox/.git" ]; then
            git clone git@github.com:deljdlx/dc_sandbox.git
          fi
          cd dc_sandbox
          git pull

          # check if .env file exists
          if [ ! -f ".env" ]; then
            echo DOMAIN=sandbox.hlb.ninja > .env
          fi

          docker compose down
          docker compose up -d





# name: Call Shared Workflow
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   call-shared-workflow:
#     uses: deljdlx/github-tools/.github/workflows/update-main-readme.yml@main
#     secrets:
#         personal_access_token: ${{ secrets.ACTION_TOKEN }}